version: "3.3"

services:
  laser-scanner:
    build:
      context: .
      dockerfile: Dockerfile
    
    image: labsolda:labsolda-laser-scanner-test
    container_name: laser-scanner

    network_mode: host

    cap_add:
      - SYS_PTRACE

    security_opt:
      - seccomp:unconfined

    environment:
      DISPLAY: "${DISPLAY}"

    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw

    stdin_open: true
    tty: true
    restart: "no"
